### ISSUE TITLE
[Request] Tribal Stage functions

### ISSUE THREAD

**Issue by VanillaCold** [emd4600/Spore-ModAPI#13]
I'm working on a hut editor mod for Spore and there just doesn't seem to be a way to change the player's hut.

It's done already by Spore whenever your hut levels up, but it always switches to specific models in the editor_rigblocks~ folder and there doesn't seem to be a way to do this manually yet with mods.

**Comment by emd4600** [comment]
What's the ID of those predefined models?

**Comment by Galaxy5151** [comment]
> What's the ID of those predefined models?

They're named `he_simple_01, `he_simple_02`, `he_simple_03`, `he_timber_01`, `he_timber_02`, `he_timber_03`, `he_yurt_01`, `he_yurt_02` and `he_yurt_03` in SporeModder FX.
